name: CI

on:
  push:
    branches: [ master ]
    tags: [ '*' ]
  workflow_dispatch:
  pull_request:
    branches: [ master ]
  schedule:
    - cron: "0 2 * * 1"

jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust:
          - stable
          - beta
          - nightly
          - '1.60.0'

    steps:
      - uses: actions/checkout@v3

      - name: Setup ${{ matrix.rust }} toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ matrix.rust }}
          override: true

      - name: Install node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: tests/lunr-fixture-gen/package-lock.json

      - name: Run lunr-fixture-gen
        run: |
          cd tests/lunr-fixture-gen
          npm install
          npm run build

      - name: Check that the fixtures haven't changed
        run: |
          git diff --exit-code tests/lunr-fixture-gen

      - name: Build (all features)
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --all-features

      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build

      - name: Test (all features)
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --all-features

      - name: Test
        uses: actions-rs/cargo@v1
        with:
          command: test
